name = "bendy-message"
main = "build/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cargo install worker-build && worker-build --release"
watch_dir = "src"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "bmsg-db"
database_name = "bendy-message-db"
database_id = "c53e5295-2ed4-47f5-ae2d-cc43584e19a7"

[[kv_namespaces]]
binding = "bmsg-cache"
id = "e942cc3d4d5e4df483a6cd52f1e5803d"

[[kv_namespaces]]
binding = "bmsg-services"
id = "4f6c6abb6694429fb6273e962ef2ffce"

[[durable_objects.bindings]]
name = "bmsg-election"
class_name = "LeaderElectionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LeaderElectionDO"]

[vars]
GITHUB_CLIENT_ID = "Ov23liSXjHPznAoeFeNv"
GITHUB_CLIENT_SECRET = "6f12408bf7cd9efd4f5b5c07cb609855e1aacc60"
